apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-Ingress
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target:/
spec:
  ingressClassName: nginx
  rules:
  - http:
    paths:
    - path: /my-path
      pathType: Prefix
      backend:
        service:
          name: server
          port:
            number: 5000